#!/usr/bin/env python3
# -*- coding: utf-8 -*-


"""
kernel.py — MasterKernel (superviseur central / noyau parent)

Vision
------


Ce que le module_cloudflare EST
---------------------


Ce que le module_cloudflare N'EST PAS
--------------------------


Composants du module_cloudflare
--------------------------


Responsabilités principales module_cloudflare
----------------------------


Interfaces attendues de module_cloudflare
---------------------


Cycle de vie du module_cloudflare(simplifié)
-------------------------



Règles d’architecture
----------------------




Notes d’évolution
------------------

"""


from module_cloudflare.config import Config
from module_cloudflare.cloudflare_client import CloudflareClient
from datetime import datetime


def main():
    cfg = Config()

    cf = CloudflareClient(
        api_token=cfg.token,
        account_id=cfg.account_id,
    )

    routes, fallback = cf.get_tunnel_routes(cfg.tunnel_id)

    print(f"Tunnel: {cfg.tunnel_id}")
    for r in routes:
        print(f"- {r.hostname} -> {r.service}")

    cfg.rewrite_autogenerated({
        "LAST_UPDATE": datetime.utcnow().isoformat(),
        "LAST_STATUS": "ok",
        "DISCOVERED_ROUTES": str(len(routes)),
    })


if __name__ == "__main__":
    main()
