from pathlib import Path
from typing import Dict

AUTOGEN_MARKER = "__AUTOGENERATED__=true"


class Config:
    def __init__(self, path: str = "module_cloudflare.conf"):
        self.path = Path(path)
        if not self.path.exists():
            raise FileNotFoundError(
                f"Config file '{self.path}' not found."
            )

        self.raw_lines = self.path.read_text(encoding="utf-8").splitlines()
        self.data = self._parse()

        # Required keys
        self.token = self._require("TOKEN")
        self.account_id = self._require("ACCOUNT_ID")
        self.tunnel_id = self._require("TUNNEL_ID")
        self.runtime_name = self.data.get("RUNTIME_NAME", "host")

    def _parse(self) -> Dict[str, str]:
        data = {}
        for line in self.raw_lines:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip().strip('"')
        return data

    def _require(self, key: str) -> str:
        if key not in self.data or not self.data[key]:
            raise ValueError(f"Missing required config key: {key}")
        return self.data[key]

    def rewrite_autogenerated(self, updates: Dict[str, str]):
        """
        Rewrite ONLY the autogenerated section.
        """
        new_lines = []
        in_autogen = False

        for line in self.raw_lines:
            if line.strip() == AUTOGEN_MARKER:
                in_autogen = True
                new_lines.append(line)
                for k, v in updates.items():
                    new_lines.append(f'{k}="{v}"')
                continue

            if in_autogen:
                # skip old autogenerated lines
                if line.startswith("#"):
                    new_lines.append(line)
                continue

            new_lines.append(line)

        self.path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

